---
layout: page
sidebar: right
title: "Caused by: ERROR XSDB6: Another instance of Derby may have already booted the database /metastore_db"
subheadline: ""
teaser: ""
tags:
  - Spark
categories:
  - Toolbox
---

## Cause

Error occurs when there exists a Spark-Shell running and holding derby DB. So when we start another Spark Shell and use DataFrame related functions, it throws this error.

## Solution

Kill the other Spark-Shell that is running and holding derby DB. 

### Step 1: Find the other Spark-Shell via the following command:
```shell 
ps -ef | grep spark-shell
```

### Step 2: Kill it

```shell
kill -9 Spark-Shell-processID ( example: kill -9 12345)
```

When it is gone, you may process DataFrame freely.